DROP DATABASE amazonia;
CREATE DATABASE amazonia;

use amazonia;

DROP TABLE IF EXISTS `orders`;

CREATE TABLE `orders`
(
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  `email` MEDIUMTEXT NULL DEFAULT NULL,
  `password` MEDIUMTEXT NULL DEFAULT NULL,
  `line1` MEDIUMTEXT NULL DEFAULT NULL,
  `line2` MEDIUMTEXT NULL DEFAULT NULL,
  `city` MEDIUMTEXT NULL DEFAULT NULL,
  `state` MEDIUMTEXT NULL DEFAULT NULL,
  `zipcode` MEDIUMTEXT NULL DEFAULT NULL,
  `card` MEDIUMTEXT NULL DEFAULT NULL,
  `expiration` MEDIUMTEXT NULL DEFAULT NULL,
  `cvv` MEDIUMTEXT NULL DEFAULT NULL,
  `billing` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
)